# Default values for website chart.

replicaCount: 1
image:
  repository: registry.gitlab.com/cedric.duboille/portfolio-wiki-camille # Adapte si besoin
  pullPolicy: IfNotPresent
  # Le tag sera mis Ã  jour par ta pipeline CI/CD !
  tag: "8346e98a426e3e954c5371b0bc30666eaf975e10"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: yukino.li # Ton nom de domaine
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: yukino-li-tls # Nom du secret pour le certificat
      hosts:
        - yukino.li
