apiVersion: v1
kind: Secret
metadata:
  name: loki-datasource-secret
  namespace: prometheus
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki-K3s
      type: loki
      uid: loki-k3s-uid
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      editable: true  # <--- SUPER IMPORTANT pour debugger
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "1"
